# Generated by Django 2.0.6 on 2019-01-26 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='item_id',
            new_name='p_k',
        ),
    ]
