# Generated by Django 2.0.6 on 2019-01-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20190126_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='pic_folder/None/no-img.jpg', null=True, upload_to='pic_folder/'),
        ),
    ]
