# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-29 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_auto_20190126_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/expenses/'),
        ),
    ]
